services:
  workspace:
    build: ./docker
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true

  php:
    image: php:8.3-fpm
    volumes:
      - .:/app
    working_dir: /app

  node:
    image: node:latest
    ports:
      - "5174:5173"
    volumes:
      - .:/app
    working_dir: /app

  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.localhost`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=web"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
